# Generated by Django 5.1.4 on 2025-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en-us', help_text='Preferred language for user interface', max_length=10, verbose_name='language'),
        ),
    ]
