# Generated by Django 5.1.4 on 2025-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Preferred timezone for user interface', max_length=25, verbose_name='timezone'),
        ),
    ]
