# Generated by Django 5.1.4 on 2025-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', help_text='Preferred language for user interface', max_length=10, verbose_name='language'),
        ),
    ]
