# Generated by Django 5.1.4 on 2025-02-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareproductcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skincareproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
