# Generated by Django 5.1.4 on 2025-01-13 00:26

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareRoutinePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='SkincareRoutineProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='SkincareRoutinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Brief description of this routine')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this routine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skincare_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_name', models.CharField(blank=True, help_text='Name of the product if not selecting from catalog', max_length=255, null=True)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('color', models.CharField(blank=True, help_text='Color code for the step (e.g. #FF0000)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('routine', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skincare_routine.skincareroutinepage')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_steps', to='skincare_routine.skincareroutineperiod')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_steps', to='skincare_routine.skincareroutineproducttype')),
            ],
            options={
                'ordering': ['sort_order', 'day_of_week'],
            },
        ),
    ]
