# Generated by Django 5.1.4 on 2025-01-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_product', '0001_initial'),
        ('skincare_routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skincareroutine',
            options={'verbose_name_plural': 'Routines'},
        ),
        migrations.AlterModelOptions(
            name='skincareroutineperiod',
            options={'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='skincareroutineproducttype',
            options={'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='skincareroutinestep',
            options={'verbose_name_plural': 'Routine Steps'},
        ),
        migrations.AddField(
            model_name='skincareroutinestep',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skincare_product.skincareproduct'),
        ),
        migrations.AddField(
            model_name='skincareroutinestep',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
