# Generated by Django 5.1.4 on 2025-02-15 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_time', models.DateTimeField(help_text='Scheduled reminder time stored in UTC')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='skincare_routine.routinestep')),
            ],
            options={
                'ordering': ['day_of_week', 'reminder_time'],
                'unique_together': {('step', 'day_of_week', 'reminder_time')},
            },
        ),
    ]
