# Generated by Django 5.1.4 on 2025-01-09 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_product', '0001_initial'),
        ('skincare_routine', '0002_alter_skincareroutine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skincareroutinestep',
            options={'ordering': ['day_of_week', 'order'], 'verbose_name_plural': 'Routine Steps'},
        ),
        migrations.AddField(
            model_name='skincareroutinestep',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_index=True, default='MON', max_length=3),
        ),
        migrations.AddField(
            model_name='skincareroutinestep',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skincareroutinestep',
            name='skincare_routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skincare_routine.skincareroutine'),
        ),
        migrations.AddIndex(
            model_name='skincareroutine',
            index=models.Index(fields=['user', 'created_at'], name='skincare_ro_user_id_3faa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='skincareroutinestep',
            index=models.Index(fields=['skincare_routine', 'day_of_week', 'order'], name='skincare_ro_skincar_459486_idx'),
        ),
    ]
