# Generated by Django 5.1.4 on 2025-02-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_product', '0003_alter_skincareproduct_created_by'),
        ('skincare_routine', '0002_stepreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinestep',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routine_steps', to='skincare_product.skincareproduct'),
        ),
    ]
