# Generated by Django 5.1.4 on 2025-01-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_routine', '0003_alter_skincareroutinestep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareroutinestep',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skincareroutinestep',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
