# Generated by Django 5.1.4 on 2025-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_routine', '0003_routinestep_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinestep',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
